### ISSUE TITLE
Additional history tracking

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#624]
We should add these to the history tracker (there's probably more):

**Nodes**
- [ ] Node creation (at the moment the tracker only works for source nodes, but we should track creation for all nodes)
  - `entity_type=NODE`
  - `activity_type=CREATE`
- [ ] Updating node:
  - `entity_type=NODE`
  - `activity_type=UPDATE`
- [ ] Deactivating node
  - `entity_type=NODE`
  - `activity_type=DEACTIVATE`
- [ ] Activating node
  - `entity_type=NODE`
  - `activity_type=ACTIVATE`
- [ ] Tagging node with tag
  - `entity_type=NODE`
  - `activity_type=TAG`
- [ ] Linking dimensions:
  - `entity_type=NODE`
  - `activity_type=LINK`
- [ ] Unlinking dimensions:
  - `entity_type=NODE`
  - `activity_type=UNLINK`
- [ ] Setting column attributes:
  - `entity_type=NODE`
  - `activity_type=SET_ATTRIBUTE`
  
**Namespaces**
- [ ] Creating a namespace:
  - `entity_type=NAMESPACE`
  - `activity_type=CREATE`
  
**Tags**
- [ ] Creating a tag:
  - `entity_type=TAG`
  - `activity_type=CREATE`
- [ ] Updating a tag:
  - `entity_type=TAG`
  - `activity_type=UPDATE`

**Comment by samredai** [comment]
Thanks for creating this, I added two to the end of the nodes section. cc: @betodealmeida @cwegener @CircArgs @agorajek , please add any other events you can think of that we'd want to track in the history table.
